:examples-gh-ref: https://github.com/michael-simons/neo4j-reactive-java-client/tree/master/examples
:examples-gh-ref-blob: https://github.com/michael-simons/neo4j-reactive-java-client/blob/master/examples

= Neo4j Reactive Java Client

image:https://travis-ci.org/michael-simons/neo4j-reactive-java-client.svg[link="https://travis-ci.org/michael-simons/neo4j-reactive-java-client"]
image:https://img.shields.io/badge/License-Apache%202.0-green.svg[link="http://www.apache.org/licenses/LICENSE-2.0"]

== Requirements

The Reactive Java Client requires Java 11 higher.
Goto http://jdk.java.net/11/[JDK 11 General-Availability Release] for binaries for you operating systems.
The Reactive Streams Java Driver does not work with an embedded version of Neo4j but needs an instance that can be addressed over the Bolt protocol.

The test infrastructure is based on https://www.testcontainers.org[Testcontainers] which in turn depend on https://docker.com[Docker].
Docker must be installed on your machine to run the integration tests.

== Concepts

The main idea is to keep as close to the official https://github.com/neo4j/neo4j-java-driver[Neo4j Java Driver] as possible.
That means, facilitating the https://neo4j.com/blog/beta-release-java-driver-async-api-neo4j/[asynchronous API] of the driver.
This has some drawbacks:
For the time being, the Neo4j Java Driver is only asynchronous.
It stops requesting records from the Server, but doesn't back pressure.
The server will keep on trying to sent stuff.

NOTE: So far handling back pressure in the reactive `Neo4jClient` as such that it just stops requesting new records and relying on the fact that the Driver than stops fetching them

Some inspiration has been drawn from the https://r2dbc.io[R2DBC specification].
R2DBC stands for _Reactive relational database connectivity_ and is an effort to bring reactive programming to relational databases.
There is a great introduction by https://twitter.com/nebhale[Ben Hale] from Spring One Platform 2018:
https://www.youtube.com/watch?v=idApf9DMdfk[Reactive relational database connectivity]
Notice one of the first slides: Reactivity is about back pressure, not being asynchronous!

The reactive `Neo4jClient` should only expose http://www.reactive-streams.org/[Reactive Streams] interfaces.
In the long run, those will be superseded by Javas https://docs.oracle.com/javase/10/docs/api/java/util/concurrent/Flow.html[Flow classes].
The reactive `Neo4jClient` internally uses https://projectreactor.io/[Project Reactor].

[[validation-against-the-reactive-streams-tck]]
=== Validation against the Reactive Streams TCK

The http://www.reactive-streams.org[Reactive Streams initiative] offers a https://github.com/reactive-streams/reactive-streams-jvm/tree/master/tck[TCK].
This TCK is meant to guide and help Reactive Streams library implementers to validate their implementations against https://github.com/reactive-streams/reactive-streams-jvm[the Reactive Streams specification].
The `Publisher` returned by the `Neo4jClient` are validated against the TCK in `org.neo4j.reactiveclient.Neo4jClientVerificationTest`.
We validate all required and optional rules.

== Examples

The link:{examples-gh-ref}[`examples`] subproject provides several examples using several implementations of Reactive Streams to get you started.
Checkout the "Hello, Worlds" using plain Reactive Streams, http://projectreactor.io[Project Reactor] and http://reactivex.io[RxJava 2] Types:

* link:{examples-gh-ref-blob}/src/main/java/org/neo4j/reactiveclient/examples/HelloWorldExampleUsingReactiveStreams.java[HelloWorld with Reactive Streams]
* link:{examples-gh-ref-blob}/src/main/java/org/neo4j/reactiveclient/examples/HelloWorldExampleUsingProjectReactor.java[HelloWorld with Project Reactor]
* link:{examples-gh-ref-blob}/src/main/java/org/neo4j/reactiveclient/examples/HelloWorldExampleUsingRxJava2.java[HelloWorld with RxJava2]

== Versioning

=== `@Deprecated`

APIs marked with the `@Deprecated annotation at the class or method level will remain supported until the next major release but it is recommended to stop using them.

== Maintainers

Michael Simons:: michael.simons@neo4j.com
Gerrit Meier:: gerrit.meier@neo4j.com
